// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCky_EwrG-0AW3icLM7AcuK36aQIc52yJ0',
    appId: '1:518185000909:web:d6921cf9195dc911d7ee84',
    messagingSenderId: '518185000909',
    projectId: 'makansmart-9d5e2',
    authDomain: 'makansmart-9d5e2.firebaseapp.com',
    storageBucket: 'makansmart-9d5e2.firebasestorage.app',
    measurementId: 'G-B3C6MXQ0LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxofqeN6sFKtTUqOIyex8mhgsqqwMH2eQ',
    appId: '1:518185000909:android:66fcc77765b328ded7ee84',
    messagingSenderId: '518185000909',
    projectId: 'makansmart-9d5e2',
    storageBucket: 'makansmart-9d5e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtIy9q3i-DtAQrjMOkR2fhGxKvDCLXqBU',
    appId: '1:518185000909:ios:538eb99fe5b71229d7ee84',
    messagingSenderId: '518185000909',
    projectId: 'makansmart-9d5e2',
    storageBucket: 'makansmart-9d5e2.firebasestorage.app',
    iosBundleId: 'com.example.makansmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtIy9q3i-DtAQrjMOkR2fhGxKvDCLXqBU',
    appId: '1:518185000909:ios:538eb99fe5b71229d7ee84',
    messagingSenderId: '518185000909',
    projectId: 'makansmart-9d5e2',
    storageBucket: 'makansmart-9d5e2.firebasestorage.app',
    iosBundleId: 'com.example.makansmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCky_EwrG-0AW3icLM7AcuK36aQIc52yJ0',
    appId: '1:518185000909:web:b629656a0f8bc0a9d7ee84',
    messagingSenderId: '518185000909',
    projectId: 'makansmart-9d5e2',
    authDomain: 'makansmart-9d5e2.firebaseapp.com',
    storageBucket: 'makansmart-9d5e2.firebasestorage.app',
    measurementId: 'G-9QCMH5NPP7',
  );
}
